[package]
authors = ["Nathan Musoke <nathan.musoke@gmail.com>"]
name = "ipfs-search"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
ipfsapi = "0.2.1"
serde_json = "1.0.11"
tantivy = "0.5.1"
tempdir = "0.3.6"
